### ISSUE TITLE
No module named 'FLIR.flir' Error Message

### ISSUE THREAD

**Issue by rob26r** [google-coral/project-teachable-sorter#12]
Has anyone else seen the error message below?  I'm using the same FLIR camera they used in the tutorial.

```
pi@raspberrypi:~/project-teachable-sorter/Sorter $ python3 sorter.py --flir
Traceback (most recent call last):
  File "sorter.py", line 158, in <module>
    import FLIR
  File "/home/pi/project-teachable-sorter/Sorter/FLIR/__init__.py", line 18, in <module>
    from .flir import FlirBFS
ModuleNotFoundError: No module named 'FLIR.flir'
```
How can I fix this?  Thanks.

**Comment by matallan** [comment]
@rob26r did you manage to fix this?

I am working from memory here - an intern of ours had the same issue and the short-cut/workaround was just to move the FLIR script into the same folder as the script - an issue with the referencing it seems.

Let me know if you haven't sorted it and can advise. They also left out a lot of the FLIR camera requirements - shutter speed etc.

**Comment by moorka2820** [comment]
What kind of camera you r using?

**Comment by manoj7410** [comment]
Does this issue still persist ?

**Comment by slingen** [comment]
In the FLIR folder there is a file named  __init__.py

.flir shoud be .FLIR  The folder name is all caps so I assume .FLIR should be all caps

#from .flir import FlirBFS

from .FLIR import FlirBFS
