### ISSUE TITLE
Error Message - missing 1 required positional argument

### ISSUE THREAD

**Issue by zhoushijun** [google-coral/project-teachable-sorter#14]
need fix this issue
pls help

> Traceback (most recent call last):
  File "/home/pi/project-teachable-sorter/Sorter/sorter.py", line 178, in <module>
    on_new_frame(engine,mean,sliding_window,send_over_ws,cam_sockets)
TypeError: on_new_frame() missing 1 required positional argument: 'cam_sockets'

**Comment by moorka2820** [comment]
Having  the same issue:

Traceback (most recent call last):
File "/home/pi/project-teachable-sorter/Sorter/sorter.py", line 178, in
on_new_frame(engine,mean,sliding_window,send_over_ws,cam_sockets)
TypeError: on_new_frame() missing 1 required positional argument: 'cam_sockets'

**Comment by moorka2820** [comment]
zhoushijun did you find the solution?

**Comment by yvesboudreau** [comment]
I beleive that you need to change line 178 to the following:

on_new_frame(cv2_im, engine, mean, sliding_window, send_over_ws, cam_sockets)

Still trying to make this work with opencv camera

**Comment by manoj7410** [comment]
@zhoushijun Were you able to fix this ?
