### ISSUE TITLE
Error Message - Unknown Resampling Filter

### ISSUE THREAD

**Issue by rob26r** [google-coral/project-teachable-sorter#9]
Hi - I am running using this command:

Python3 sorter.py --opencv

**Why am I getting this error message?**

```
Traceback (most recent call last):
  File "sorter-copy.py", line 174, in <module>
    pil_im.resize(224, 224)
  File "/usr/lib/python3/dist-packages/PIL/Image.py", line 1784, in resize
    raise ValueError("unknown resampling filter")
ValueError: unknown resampling filter
```

**Comment by zhoushijun** [comment]
transforms.Resize(224, 224) ----》transforms.Resize((224, 224))
